---
- name: Install required packages for Grafana
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ required_packages }}"
  become: yes

- name: Install Grafana
  become: yes
  apt:
    name: grafana
    state: present

- name: Copy Grafana configuration file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
